config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get '/home', to: 'pages#home'
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post '/recipes', to:'recipes#create'
  #get 'recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch 'recipes/:id', to: 'recipes#update'
  #get 'recipes/:id', to: 'recipes#show', as:'recipe'
  #delete 'recipes/:id', to:'recipes#destroy'

  resources :recipes do
   member do
     post 'like'
     post 'review'
     delete 'review', to: "recipes#deletereview"
   end
  
  end
  
  resources :chefs, except: [:new, :destroy]
  get '/register', to: 'chefs#new'

  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :chef
    has_many :likes, dependent: :destroy 
    has_many :recipe_styles, dependent: :destroy
    has_many :styles, through: :recipe_styles
    has_many :recipe_ingredients, dependent: :destroy 
    has_many :ingredients, through: :recipe_ingredients
    has_many :reviews, dependent: :destroy
    
    validates :chef_id, presence: true
    validates :name, presence: true, length:{minimum:5, maximum: 100}
    validates :summary, presence: true, length:{minimum:10, maximum: 150}
    validates :description, presence: true, length:{minimum:20, maximum: 500}
    mount_uploader :picture, PictureUploader
    validate :picture_size
    default_scope -> { order(updated_at: :desc) }
    
    def thumbs_up_total
    self.likes.where(like: true).size
    end
    
    def thumbs_down_total
    self.likes.where(like: false).size
    end
    
    private 
        def picture_size
          if picture.size > 5.megabytes
              errors.add(:picture, "should be less than 5MB")
            end
        end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   before_action :set_recipe, only: [:edit, :update, :show, :like, :review]
   before_action :require_user, except: [:show, :index, :like]
   before_action :require_user_like, only: [:like]
   before_action :require_same_user, only: [:edit, :update]
   before_action :admin_user, only: :destroy
   
   def index
      @recipes = Recipe.paginate(page: params[:page], per_page: 4)
   end
   
   def show
      
   end
   
   def new
      @recipe = Recipe.new
   end
   
   def create
      @recipe = Recipe.new(recipe_params)
      @recipe.chef = current_user
      
      if @recipe.save
         flash[:success] = "Your Recipe Was Created Successfully"
         redirect_to recipes_path
         
      else render :new
         
      end
   end
   
   def edit
     
   end
   
   
   def update
      
      if @recipe.update(recipe_params)
         flash[:success] = "Your recipe was updated sccessfully!"
         redirect_to recipe_path(@recipe)
      else
         render :edit
      end
   end
   
  def review
    review = Review.create(comment: params[:comment], chef: current_user, recipe: @recipe)
    if review.valid?
      flash[:success] = "Thank you for reviewing this recipe"
    else
      flash[:danger] = "Review failed to post"
    end
    redirect_to :back
  end
  
  def deletereview
    Review.find(params[:revid]).destroy
    flash[:success] = "Review deleted"
    redirect_to :back
  end
   
   def like
      
      like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
      if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_to :back
      else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to :back
   end
   end
   
   def destroy
      Recipe.find(params[:id]).destroy
      flash[:success] = "Recipe Deleted"
      redirect_to recipes_path
   end
   
   private 
   
   def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids: [])
   end
   
   def set_recipe
      @recipe = Recipe.find(params[:id])
   end
   
   def require_same_user
            if current_user != @recipe.chef and !current_user.admin?
            
                flash[:danger] = "You can only edit your own recipes"
                redirect_to recipes_path
            end
   end
   
  def require_user_like
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to :back
    end
  end
  
  def admin_user
   redirect_to recipes_path unless current_user.admin?
  end

end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        
        <%= form_for(@recipe, html: { multipart:true }) do |f| %>
        
        <%= f.label :name %>
        <%= f.text_field :name %>
        
        <%= f.label :summary%>
        <%= f.text_field :summary%>
        
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10%>
        
        <strong>Styles:</strong>
        <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
        <br><br>
        
        <strong>Ingredients:</strong>
        <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
            <% cbi.label(class: "checkbox-inline input_checkbox") {cbi.check_box(class: "checkbox") + cbi.text} %>
        <% end %>
        <br><br>
        
        <span class="picture">
            <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
        </span>
        
        <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class:"btn btn-success")%>
        <% end %>
    </div>
    
</div>


<script type="text/javascript">
    $('#recipe_picture').bind('change', function(){
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5){
            alert('Maximum file size is 5MB. Please choose a smaller file');
        }
    });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>


<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<ul class="nav nav-tabs">
    <li class="active">
        <%= link_to "Recipes", recipes_path %>
    </li>
    
    <li>
        <%= link_to "Chefs", chefs_path %>
    </li>
</ul>

<%= will_paginate %>

<% @recipes.each do |recipe| %>
    <div class ="row" >
        <div class= "col-md-2">
            <section class="chef_info center">
                <%= link_to gravatar_for(recipe.chef, size:100), chef_path(recipe.chef) %>
                <h5>Chef Name: <%= recipe.chef.chefname %></h5>
            </section>
            
        </div>
        
          <div class= "col-lg-6 well">
              <h4> <%= link_to recipe.name,recipe_path(recipe) %></h4>
              <p><%=recipe.summary%></p>
              
              <% if recipe.styles.any? %>
              <p>Styles: <%= render recipe.styles %></p>
              <% end %> 
             
               <% if recipe.ingredients.any? %>
              <p>Ingredients: <%= render recipe.ingredients %></p>
              <% end %>
              
              <p>
              <span class="quiet"><small> created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
              <span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
                  
              </span>
              </p>
              <div class="pull-right">
                <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                 <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
                <% end %> &nbsp&nbsp&nbsp&nbsp
                
                <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                 <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
                <% end %>
                
              </div>
          </div>
        <div class="col-md-4">
          <%= image_tag(recipe.picture.url, size: "250x150", class:"gravatar") if recipe.picture? %>
        </div>
    </div>
    
   
     
     
<hr/>

<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new recipe" %>


<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>


<div class="row">
    <div class="col-md-4 pull-right center">
        <%= link_to gravatar_for(@recipe.chef, size:200), chef_path(@recipe.chef) %>
        <p>
            <h5>Brought to you by: <%=@recipe.chef.chefname %></h5>
        </p>
    </div>
    
    <div class="col-md-8">
        
        <% if logged_in? and (@recipe.chef == current_user || current_user.admin?) %>
            <%= link_to "Edit this Recipe", edit_recipe_path(@recipe), class:"btn btn-success pull-right" %>
        <%end%>
        
        <% if logged_in? and current_user.admin? %>
            <%= link_to "[Delete Recipe]", @recipe, method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
        
        <h3><%= @recipe.summary %></h3>
        <div class="show_recipe">
            <%= image_tag(@recipe.picture.url, class:"gravatar") if @recipe.picture? %>
        </div>
        <div class="well">
            
            <% if @recipe.styles.any? %>
            <p>Styles: <%= render @recipe.styles %></p>
            <% end %>
            
            <% if @recipe.ingredients.any? %>
            <p>Ingredients: <%= render @recipe.ingredients %></p>
            <% end %>
            
            <p>
                <strong>Steps:</strong>
            </p>
            <%= simple_format(@recipe.description) %>
            <div class="pull-right">
                <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
                 <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total %>
                <% end %> &nbsp&nbsp&nbsp&nbsp
                
                <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
                 <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total %>
                <% end %>
                
            </div>
        </div>
        
        <h3>Reviews:</h3>
        <% if @recipe.reviews.any? %>
        <% @recipe.reviews.each do |c| %>
        
        <div class="well">
        
            <p>
                <h5>Reviewer: <%= c.chef.chefname %></h5>    
                <h5>Comment: <%= c.comment %></h5>
                <h5>Created at: <%= c.created_at %></h5>
            </p>
            
        </div>
          
          <% if c.chef == current_user %>
    
            <%= link_to "Delete Review", review_recipe_path(:revid => c.id), class:"btn btn-danger btn-small pull-right definer", method: :delete, data: { confirm: "Are you sure you want to delete this review?" }  %>
          <% end %>
        
        <% end %>
        <% end %>
        
        <% if logged_in? %>
          <div class="form-group">
            <%= form_tag(review_recipe_path, method: :post) do %>
              <%= text_area_tag "comment", nil, size:"5x5",  class:"form-control" %>
              <%= submit_tag "Submit Review", class: "btn btn-primary" %> <br/><br/>
          </div>
          <% end %>
        
        <% else %>
        <h5>
          <%= link_to "Log In", login_path %> or
          <%= link_to "Sign Up", register_path %> 
          To Leave Your Comment As The First One
         </h5>
        <% end %>
    </div>

</div>



<h5><%= link_to "Return to Recipes Listing", recipes_path, class: "btn btn-warning btn-small" %></h5>