config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get '/home', to: 'pages#home'
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post '/recipes', to:'recipes#create'
  #get 'recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch 'recipes/:id', to: 'recipes#update'
  #get 'recipes/:id', to: 'recipes#show', as:'recipe'
  #delete 'recipes/:id', to:'recipes#destroy'

  resources :recipes do
   member do
     post 'like'
     post 'review'
     delete 'review', to: "recipes#deletereview"
   end
  
  end
  
  resources :chefs, except: [:new, :destroy]
  get '/register', to: 'chefs#new'

  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
end

app/views/pages/home.html.erb
<div class="center jumbotron home-back">
    <h1>Welcome to MyRecipes App</h1>
    
    <h2>This is a professional Ruby on Rails Courses</h2>
    
    <%= link_to "Sign Up Now!", register_path, class: "btn btn-lg btn-success" %>
</div>

<div class="row">
    <div class="col-lg-4">
        <h3 class="midrow">
            View Recipes as Guest Users
        </h3>
        
        <h2 class="left">
            Browse and view recipes as guest and sign up later
        </h2>
        
        <p>
            <%= link_to "Browse Recipes Listings",recipes_path,class:"btn btn-warning btn-small" %>
        </p>
        
    </div>
    
        <div class="col-lg-4">
        <h3 class="midrow">
            Sign in to your account
        </h3>
        
        <h2 class="left">
            Add/Update your recipes/create reviews/like-dislike recipes and much much more
        </h2>
        
        <p>
            <%= link_to "Log in to your account", login_path ,class:"btn btn-warning btn-small" %>
        </p>
        
    </div>
    
        <div class="col-lg-4">
        <h3 class="midrow">
            View Recipes as Guest Users
        </h3>
        
        <h2 class="left">
            Browse and view recipes as guest and sign up later
        </h2>
        
        <p>
            <%= link_to "Browse Recipes Listings","",class:"btn btn-warning btn-small" %>
        </p>
        
    </div>
    
</div>